global using System.ComponentModel.DataAnnotations;
global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.Azure.Functions.Worker;
global using Microsoft.Azure.Functions.Worker.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;